import {useEffect,useState} from 'react';
const API='http://localhost:8080/api';
const token=()=>localStorage.getItem('shiptrackToken');
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(options.headers||{})}});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok)throw Error(d.message||'Request failed');return d}
function Auth({onLogin}){const[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
const submit=async e=>{e.preventDefault();setMsg('');setLoading(true);try{const r=await fetch(API+'/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.message||'Request failed');localStorage.setItem('shiptrackToken',d.token);localStorage.setItem('shiptrackUser',JSON.stringify(d));onLogin(d)}catch(e){setMsg(e.message)}finally{setLoading(false)}};
return <main className="page"><section className="card"><div className="brand"><div className="logo">S</div><div><h1>ShipTrack Pro</h1><p>Shipment Tracking & Delivery Visibility</p></div></div><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Login</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Register</button></div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p className="sub">{mode==='login'?'Sign in to manage and track shipments.':'Register to start managing your shipments.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label>}<label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input type="password" required minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Minimum 6 characters"/></label><button className="submit" disabled={loading}>{loading?'Please wait...':mode==='login'?'Login':'Create account'}</button></form>{msg&&<div className="error">{msg}</div>}<p className="footer">Secure JWT authentication • Spring Boot • PostgreSQL</p></section></main>}
function Dashboard({user,onLogout}){const[shipments,setShipments]=useState([]),[track,setTrack]=useState(''),[selected,setSelected]=useState(null),[msg,setMsg]=useState(''),[form,setForm]=useState({sender:'',receiver:'',origin:'',destination:''}),[showCreate,setShowCreate]=useState(false);
const load=async()=>{try{setShipments(await request('/shipments'))}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);
const create=async e=>{e.preventDefault();try{await request('/shipments',{method:'POST',body:JSON.stringify(form)});setForm({sender:'',receiver:'',origin:'',destination:''});setShowCreate(false);setMsg('Shipment created successfully');load()}catch(e){setMsg(e.message)}};
const find=async e=>{e.preventDefault();try{setSelected(await request('/shipments/'+track.trim()))}catch(e){setMsg('Shipment not found')}};
return <main className="dashboard"><header><div><b>ShipTrack Pro</b><span> Shipment Tracking & Delivery Visibility</span></div><button onClick={onLogout}>Logout</button></header><section className="welcome"><h1>Welcome, {user.name} 👋</h1><p>Manage shipments, monitor delivery status and track packages.</p></section><div className="stats"><div><small>Total Shipments</small><strong>{shipments.length}</strong></div><div><small>In Transit</small><strong>{shipments.filter(s=>s.status==='IN_TRANSIT').length}</strong></div><div><small>Delivered</small><strong>{shipments.filter(s=>s.status==='DELIVERED').length}</strong></div></div><section className="actions"><form onSubmit={find}><input value={track} onChange={e=>setTrack(e.target.value)} placeholder="Enter tracking number e.g. ST..." required/><button>Track Shipment</button></form><button onClick={()=>setShowCreate(!showCreate)}>{showCreate?'Close':'＋ Create Shipment'}</button></section>{showCreate&&<section className="panel"><h2>Create Shipment</h2><form className="gridform" onSubmit={create}>{['sender','receiver','origin','destination'].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button className="submit">Create Shipment</button></form></section>}{selected&&<section className="panel"><div className="panelHead"><h2>Tracking Result</h2><button onClick={()=>setSelected(null)}>Close</button></div><ShipmentCard s={selected}/></section>}<section className="panel"><div className="panelHead"><h2>All Shipments</h2><button onClick={load}>Refresh</button></div>{shipments.length===0?<p className="empty">No shipments yet. Create your first shipment above.</p>:shipments.map(s=><ShipmentCard key={s.id} s={s}/>)}</section>{msg&&<div className="toast">{msg}</div>}</main>}
function ShipmentCard({s}){return <article className="shipment"><div><b>{s.trackingNumber}</b><p>{s.origin} → {s.destination}</p><small>Current location: {s.currentLocation||'-'} · ETA: {s.estimatedDelivery?new Date(s.estimatedDelivery).toLocaleDateString():'-'}</small></div><span>{s.status.replaceAll('_',' ')}</span></article>}
function App(){const[user,setUser]=useState(()=>JSON.parse(localStorage.getItem('shiptrackUser')||'null'));if(!user)return <Auth onLogin={setUser}/>;return <Dashboard user={user} onLogout={()=>{localStorage.clear();setUser(null)}}/>}export default App;